// def n obj which returns n array
const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: '10',
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/d2.jpg',
      price: 250,
      countInStock: 20,
      brand: ' Adidas',
      rating: '4.0',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/d3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: '4.5',
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p1.jpg',
      price: 65,
      countInStock: 5,
      brand: ' Adidas',
      rating: '4.5',
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
